application: w8p-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /vendor
  static_dir: static/vendor

- url: /
  static_dir: static/production

libraries:
- name: webapp2
  version: "latest"
